/*
 * Channel API
 * Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.io.File;
import com.konfigthis.client.model.InboundMessage;
import com.konfigthis.client.model.InboundMessageMetadata;
import com.konfigthis.client.model.InboundMessageSender;
import com.konfigthis.client.model.MessagesImportReceivedMessageResponse;
import com.konfigthis.client.model.OutboundMessage;
import com.konfigthis.client.model.OutboundMessageToInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MessagesApi
 */
@Disabled
public class MessagesApiTest {

    private static MessagesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new MessagesApi(apiClient);
    }

    /**
     * Sync inbound message
     *
     * Import a message that was received by the channel.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importReceivedMessageTest() throws ApiException {
        InboundMessageSender sender = null;
        String body = null;
        InboundMessageMetadata metadata = null;
        String channelId = null;
        String subject = null;
        Integer deliveredAt = null;
        List<File> attachments = null;
        MessagesImportReceivedMessageResponse response = api.importReceivedMessage(sender, body, metadata, channelId)
                .subject(subject)
                .deliveredAt(deliveredAt)
                .attachments(attachments)
                .execute();
        // TODO: test validations
    }

    /**
     * Sync outbound message
     *
     * Import a message that was sent from the channel.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importSyncedMessageTest() throws ApiException {
        List<OutboundMessageToInner> to = null;
        String body = null;
        InboundMessageMetadata metadata = null;
        String channelId = null;
        String senderName = null;
        String subject = null;
        String authorId = null;
        Integer deliveredAt = null;
        List<File> attachments = null;
        MessagesImportReceivedMessageResponse response = api.importSyncedMessage(to, body, metadata, channelId)
                .senderName(senderName)
                .subject(subject)
                .authorId(authorId)
                .deliveredAt(deliveredAt)
                .attachments(attachments)
                .execute();
        // TODO: test validations
    }

}
